### ISSUE TITLE
Fatal error due to mising emthod

### ISSUE THREAD

**Issue by davidmaack** [hofff/contao-language-relations-news#1]
>  Fatal error: Class Hofff\Contao\LanguageRelations\News\Util\ContaoNewsUtil contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Contao\Module::compile) in /var/www/entwicklung/davidmaack/contao_3.5/composer/vendor/hofff/contao-language-relations-news/src/Util/ContaoNewsUtil.php on line 10

The Class Hofff\Contao\LanguageRelations\News\Util\ContaoNewsUtil misses the compile method, because it extends the abstrac class \Module. Please add an empty compile method or extend the \ModuleNewsReader

**Comment by backbone87** [comment]
fixed in 29bfb653927f7a113207e160ebd8baef81353a54
