### ISSUE TITLE
Dieses Element wird nicht übersetzt, da keine Elemente anderer Sprachen in der Übersetzungsgruppe dieses Elements gefunden wurden. 

### ISSUE THREAD

**Issue by bibib** [hofff/contao-language-relations-news#2]
Nein, das ist natürlich kein Fehler, aber ich hab leider keinen Schimmer, wie ich die Newsarchive übersetzt bekomme. Da ich im Contao-Forum leider bis jetzt keine Antwort bekommen habe, dachte ich, ich frage hier mal vorsichtig nach einem Hinweis: [*klick*](https://community.contao.org/de/showthread.php?68109-hofff-contao-language-relations-news-keine-Elemente-anderer-Sprachen-gefunden&p=451260#post451260)

**Comment by frontendschlampe** [comment]
Danke für den Hinweis ... weiter geht's im Forum! :-)
